# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
cach:
  directories:
  -$HOME/.m2


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


env:
  global:
    - CODECOV_TOKEN="6e598dd8-c945-4203-9b70-bf63780e4320"
    -
notifications:
  email:

    recipients:
      -demonick82@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
